apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: janitorr-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.logVolumeSize }}
  storageClassName: {{ .Values.persistence.logVolumeStorageClass }}
